'use client';

import Footer from '@/components/Footer';
import Nav from '@/components/Nav';
import type { Metadata } from 'next';
import './globals.scss';
import { Suspense } from 'react';

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <Suspense>
        {children}
        </Suspense>
        <Footer />
      </body>
    </html>
  );
}
