'use client';

import Footer from '@/components/Footer';
import Nav from '@/components/Nav';
import type { Metadata } from 'next';
import './globals.scss';
import { Suspense } from 'react';
import { QueryClient, QueryClientProvider } from 'react-query';

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = new QueryClient();

  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={client}>
          <Nav />
          <Suspense>{children}</Suspense>
          <Footer />
        </QueryClientProvider>
      </body>
    </html>
  );
}
